"""Case package creation and synthetic assembly helpers."""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from endpoint_incident_triage import SCHEMA_VERSION, TOOL_NAME, __version__
from endpoint_incident_triage.custody import append_record
from endpoint_incident_triage.evidence_paths import (
    create_case_directory,
    ensure_package_layout,
    package_layout,
    set_restrictive_permissions,
    validate_case_id,
)
from endpoint_incident_triage.models import CaseMetadata, CollectorResult, CustodyRecord
from endpoint_incident_triage.statuses import SourceMode
from endpoint_incident_triage.timestamps import utc_now_iso

README_TEMPLATE = """\
endpoint-incident-triage evidence package
=========================================

{synthetic_notice}SENSITIVITY WARNING
-------------------
This package may contain endpoint state, user identifiers, network metadata,
file paths, security-event summaries, and other data relevant to incident
response. Handle according to organizational policy. Do not share publicly
without appropriate privacy review.

This package is NOT encrypted. Transport and storage protections are the
operator's responsibility.

Tamper-evident custody records and SHA-256 manifests support consistency
verification but do not prove legal admissibility or endpoint cleanliness.

Package ID: {package_id}
Case ID: {case_id}
Source mode: {source_mode}
Generated by: {tool_name} {tool_version}
"""

SYNTHETIC_README_NOTICE = """\
SYNTHETIC DEMONSTRATION DATA
----------------------------
This package contains synthetic endpoint-triage data created exclusively for
demonstration, testing, and documentation purposes. No real endpoint was
inspected.

"""


@dataclass(slots=True)
class CaseContext:
    case_dir: Path
    layout: dict[str, Path]
    metadata: CaseMetadata
    package_id: str
    custody_ledger: list[CustodyRecord]


def build_package_id(case_id: str, stamp: str) -> str:
    """Build a stable package identifier."""
    validate_case_id(case_id)
    return f"case-{case_id}-{stamp}"


def create_case_metadata(
    *,
    case_id: str,
    authorization_reference: str,
    operator_label: str,
    collection_reason: str,
    target_label: str,
    platform: str,
    profile: str,
    source_mode: SourceMode,
    started_at_utc: str | None = None,
    completed_at_utc: str | None = None,
    limitations: list[str] | None = None,
) -> CaseMetadata:
    """Create validated case metadata."""
    validate_case_id(case_id)
    started = started_at_utc or utc_now_iso()
    return CaseMetadata(
        case_id=case_id,
        collection_id=str(uuid.uuid4()),
        authorization_reference=authorization_reference,
        operator_label=operator_label,
        collection_reason=collection_reason,
        target_label=target_label,
        started_at_utc=started,
        completed_at_utc=completed_at_utc,
        source_mode=source_mode,
        platform=platform,
        tool_version=__version__,
        profile=profile,
        limitations=limitations or [],
    )


def write_readme(layout: dict[str, Path], *, package_id: str, metadata: CaseMetadata) -> None:
    """Write README.txt with sensitivity warning."""
    synthetic_notice = (
        SYNTHETIC_README_NOTICE if metadata.source_mode == SourceMode.SYNTHETIC else ""
    )
    text = README_TEMPLATE.format(
        synthetic_notice=synthetic_notice,
        package_id=package_id,
        case_id=metadata.case_id,
        source_mode=metadata.source_mode.value,
        tool_name=TOOL_NAME,
        tool_version=__version__,
    )
    readme_path = layout["root"] / "README.txt"
    readme_path.write_text(text, encoding="utf-8")
    set_restrictive_permissions(readme_path)


def write_case_metadata_files(layout: dict[str, Path], metadata: CaseMetadata) -> None:
    """Write metadata JSON documents."""
    metadata_dir = layout["metadata"]
    metadata_dir.mkdir(parents=True, exist_ok=True)
    case_doc = metadata.to_dict()
    (metadata_dir / "case.json").write_text(
        json.dumps(case_doc, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    collection_doc = {
        "schema_version": SCHEMA_VERSION,
        "collection_id": metadata.collection_id,
        "started_at_utc": metadata.started_at_utc,
        "completed_at_utc": metadata.completed_at_utc,
        "profile": metadata.profile,
        "platform": metadata.platform,
        "source_mode": metadata.source_mode.value,
        "limitations": metadata.limitations,
    }
    (metadata_dir / "collection.json").write_text(
        json.dumps(collection_doc, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    tool_doc = {
        "schema_version": SCHEMA_VERSION,
        "tool_name": TOOL_NAME,
        "tool_version": __version__,
        "generated_at_utc": utc_now_iso(),
    }
    (metadata_dir / "tool.json").write_text(
        json.dumps(tool_doc, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    host_context = {
        "schema_version": SCHEMA_VERSION,
        "target_label": metadata.target_label,
        "platform": metadata.platform,
        "source_mode": metadata.source_mode.value,
    }
    (metadata_dir / "host-context.json").write_text(
        json.dumps(host_context, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def write_collector_artifact(
    layout: dict[str, Path],
    result: CollectorResult,
) -> Path:
    """Write a collector result JSON artifact."""
    platform_dir = layout["artifacts"] / result.platform
    platform_dir.mkdir(parents=True, exist_ok=True)
    target = platform_dir / f"{result.collector_id}.json"
    target.write_text(
        json.dumps(result.to_dict(), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    set_restrictive_permissions(target)
    return target


def write_collector_execution_log(
    layout: dict[str, Path],
    entries: list[dict[str, Any]],
) -> None:
    """Write collector execution log as JSONL."""
    log_path = layout["logs"] / "collector-execution.jsonl"
    log_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        json.dumps(entry, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
        for entry in entries
    ]
    log_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def initialize_case_package(
    output_parent: Path,
    *,
    case_id: str,
    stamp: str,
    metadata: CaseMetadata,
    actor_label: str,
) -> CaseContext:
    """Create case directory layout and initial custody record."""
    package_id = build_package_id(case_id, stamp)
    case_dir = create_case_directory(output_parent, case_id, stamp)
    layout = ensure_package_layout(case_dir)
    write_readme(layout, package_id=package_id, metadata=metadata)
    write_case_metadata_files(layout, metadata)
    reports_placeholder = layout["reports"] / "README.txt"
    reports_placeholder.write_text(
        "Generated triage reports may be placed in this directory.\n",
        encoding="utf-8",
    )
    set_restrictive_permissions(reports_placeholder)

    ledger: list[CustodyRecord] = []
    append_record(
        ledger,
        event_type="case_created",
        package_id=package_id,
        actor_label=actor_label,
        action="create_case_package",
        details={
            "case_id": metadata.case_id,
            "source_mode": metadata.source_mode.value,
            "platform": metadata.platform,
            "profile": metadata.profile,
        },
        occurred_at_utc=metadata.started_at_utc,
    )

    return CaseContext(
        case_dir=case_dir,
        layout=layout,
        metadata=metadata,
        package_id=package_id,
        custody_ledger=ledger,
    )


def write_findings_json(layout: dict[str, Path], findings: list[dict[str, Any]]) -> Path:
    """Write findings.json artifact."""
    path = layout["findings"] / "findings.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    document = {"schema_version": SCHEMA_VERSION, "findings": findings}
    path.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path
